client/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')), #Main appinin urlerini burayada yazabiliriz, bu sekilde kodu yonetmesi daha kolay, main urlleri buraya da ekledik
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'},
        name='login'), #name yazdigimiz template icerisine girdigimiz action urlsindekileri ifade ediyor. template icindekiler bunlari nameleri ile taniyor
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'},
        name='logout'),

]

main/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'main'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^rooms/(?P<hotel_code>[\w-]+)', views.rooms, name='rooms'),
    url(r'^hotels/$', views.hotels, name='hotels'),
    url(r'^room/(?P<product_code>[\w-]+)', views.room, name='room'),
    url(r'^book/$', views.book, name='book'),
    url(r'^confirmation/(?P<confirmation_code>[\w-]+)', views.confirmation,
        name='confirmation'),
    url(r'^mybookings/$', views.mybookings, name='mybookings'),

]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import django.contrib.auth.models as auth_models


class Hotel(models.Model):
    name = models.CharField(max_length=100)
    coral_code = models.CharField(max_length=100, unique=True)


class Destination(models.Model):
    name = models.CharField(max_length=100)
    coral_code = models.CharField(max_length=100, unique=True)


class MyTokens(models.Model):
    token_id = models.CharField(max_length=100, unique=True)
    used_flag = models.BooleanField(default=False)
    creation_time = models.CharField(max_length=100, null=True)


class MyBookings(models.Model):
    user = models.ForeignKey(auth_models.User, related_name='user')
    provision_code = models.CharField(max_length=255)
    hotel_code = models.CharField(max_length=50)
    hotel_name = models.CharField(max_length=50)
    coral_booking_code = models.CharField(max_length=255)
    room_type = models.CharField(max_length=50)
    room_description = models.CharField(max_length=255)
    pax_count = models.IntegerField()
    pax_names = models.TextField()
    price = models.FloatField()
    email = models.EmailField()
    book_time = models.CharField(null=True,max_length=50)

main/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response, HttpResponse
from django.contrib.auth.decorators import login_required
import json
from main.models import Hotel, Destination, MyTokens, MyBookings
from coral_client import book
import time
import redis
from django.conf import settings
from tokengenerate import AliToken
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives


redis_obj = redis.StrictRedis(host='localhost', port=6379)
domain_name = 'http://127.0.0.1:8080'

book_instance = book.Book()
book_instance.login(settings.API_USERNAME, settings.API_PASSWORD)


@login_required()
def index(request):
    all_entries = Destination.objects.all()
    return render(request, 'main/index.html', {"destinations": all_entries})


@login_required()
def hotels(request):
    # Butun degerleri tek satirda alabilir miyiz?
    pax = request.GET.get('pax')
    checkin_date = request.GET.get('check_in_date')
    checkout_date = request.GET.get('check_out_date')
    destination_code = request.GET.get('destination_code')
    search_params = {'checkin': str(checkin_date),
                     'checkout': str(checkout_date),
                     'pax': str(pax),
                     'destination_code': destination_code,
                     'client_nationality': 'tr',
                     'currency': 'USD'}

    try:
        result = cache_control_search(search_params)
    except ValueError:
        return render_to_response('main/error.html')

    hotel_static = Hotel.objects.values_list('coral_code')
    redis_obj.set('pax_count', json.dumps(pax), ex=3600)
    redis_obj.set('checkin_date', json.dumps(checkin_date), ex=3600)
    redis_obj.set('checkout_date', json.dumps(checkout_date), ex=3600)

    context = [{'hotel_obj_name':
               Hotel.objects.get(coral_code=pro['hotel_code']).name,
               'final_price': min_price(pro), 'hotel_code': pro['hotel_code']}
               for pro in result['results'] if (pro['hotel_code'],)
               in hotel_static]

    # values
    # for product in result['results']:
    #     if (product['hotel_code'],) in hotel_static: #
    # Tek elemanli tuple kontrolu aksi halde false donuyor.
    #         hotel_obj = Hotel.objects.get(coral_code=product['hotel_code'])
    #         final_price = min_price(hotel=product)
    #         hotel_code = product['hotel_code']
    #         context.append({'hotel_obj_name': hotel_obj.name, '
    # final_price': final_price, 'hotel_code': hotel_code})
    if len(context) > 0:
        return render(request, 'main/hotels.html', {"hotels_info": context})
    else:
        return render_to_response('main/noroom.html')


@login_required()
def rooms(request, hotel_code):
    hotel_src_par = {'checkin': json.loads(redis_obj.get('checkin_date')),
                     'checkout': json.loads(redis_obj.get('checkout_date')),
                     'pax': json.loads(redis_obj.get('pax_count')),
                     'hotel_code': hotel_code,
                     'client_nationality': 'tr',
                     'currency': 'USD'}
    redis_obj.set('hotel_code', json.dumps(hotel_code), ex=3600)

    redis_obj.set('hotel_code', json.dumps(hotel_code), ex=3600)

    try:
        result = \
            book_instance.search(hotel_src_par)[0]['results'][0]['products']
    except:
        return render_to_response('main/error.html')

    hotel_obj = Hotel.objects.get(coral_code=hotel_code)
    redis_obj.set('hotel_name', json.dumps(hotel_obj.name), ex=3600)
    sorted_room = sorted(result, key=lambda k: float(k['price']))
    # request.session['hotel_name'] = hotel_obj.name
    return render(request, 'main/rooms.html',
                  {'room_list': sorted_room,
                   'hotel_obj_name': hotel_obj.name})


def room(request, product_code):
    try:
        availability_result = cache_control_availability(product_code)
    except ValueError:
        return render_to_response('main/error.html')
    pax_generator = xrange(int(json.loads(redis_obj.get('pax_count'))))
    redis_obj.set('product_code', json.dumps(product_code), ex=3600)

    # checkout =
    # datetime.strptime(str(request.session['checkout_date']), '%Y-%m-%d')
    # checkin =
    # datetime.strptime(str(request.session['checkin_date']), '%Y-%m-%d')
    total_price = availability_result[0]['price']
    # price_per_night = float(total_price) * int((checkout - checkin).days)

    if availability_result[1] == 200:
        return render(request, 'main/book.html',
                      {'availability_result': availability_result,
                       'pax_generator': pax_generator,
                       'hotel_name': json.loads(redis_obj.get('hotel_name')),
                       'final_price': total_price,
                       'product_code': product_code})
    else:
        return render(request, 'main/noroom.html', {'param': 'room_not_ava'})


@login_required()
def book(request):
    pax = []
    names_surnames = []
    if request.method == "POST":
        product_code = request.POST.get('product_code', 'pax_name')
        mail = str(request.POST.get('mail'))
        redis_obj.set('mail', json.dumps(mail), ex=3600)
        pax_name = request.POST.getlist('pax_name')
        # pax_count = request.session['pax']
        for name in pax_name:
            name_list = name.split()
            last_name = name_list[-1]
            name_list.pop()
            first_name = ' '.join(name_list)
            names_surnames.append((first_name, last_name))
            pax.append('1,{},{},adult'.format(first_name, last_name))

        # request.session['pax_list'] = pax
        redis_obj.set('names_surnames', json.dumps(names_surnames), ex=3600)

        redis_obj.set('pax_list', json.dumps(pax), ex=3600)

        # if total_pax != '':
        #     total_pax = total_pax + '&' + pax +
        # else:
        #     total_pax = pax_count + ',' + pax
        # with cf.ThreadPoolExecutor(max_workers=1) as executor:
        #     executor.submit(send_confirmation_mail, request, mail,
        #                     cache_control_availability(product_code)
        #                     )
        send_confirmation_mail(request, mail,
                               cache_control_availability(product_code))
    return HttpResponse('Check your e-mail to confirm your book ')


@login_required()
def confirmation(request, confirmation_code):
    current_user = request.user
    tokenobj = AliToken()
    product_code = json.loads(redis_obj.get('product_code'))
    mail_token = confirmation_code
    creation_time = MyTokens.objects.get(token_id=mail_token).creation_time
    static_token = MyTokens.objects.get(token_id=mail_token)
    if tokenobj.check_token(current_user, token=mail_token) \
            and not MyTokens.objects.get(token_id=mail_token).used_flag \
            and tokenobj.token_life_time(creation_time):
        static_token.used_flag = True
        static_token.save()
        pro_result = book_instance.provision(product_code)

        if float(pro_result[0]['price']) == \
                float(cache_control_availability(product_code)[0]['price']):
            book_result = book_instance.book(
                provision_code=pro_result[0]['code'],
                book_info={'name': json.loads(redis_obj.get('pax_list'))})
            if book_result[1] == 200:
                # pax_names = json.loads(redis_obj.get('pax_list'))
                # # for pax in pax_names:
                # #
                # # #pax_name = ' '.join(pax_names)
                pax_names = json.loads(redis_obj.get('names_surnames'))
                names = ''
                for item in pax_names:
                    names += item[0] + ' ' + item[1] + ','

                room_type = str(book_result[0]['confirmation_numbers'][0]
                                ['rooms'][0]['room_type'])

                book_code = book_result[0]['code']
                room_description = str(book_result[0]
                                       ['confirmation_numbers'][0]['rooms']
                                       [0]['room_description'])

                pax_count = json.loads(redis_obj.get('pax_count'))
                price = pro_result[0]['price']
                mail = json.loads(redis_obj.get('mail'))
                hotel_code = json.loads(redis_obj.get('hotel_code'))
                provision_code = pro_result[0]['code']
                hotel_name = json.loads(redis_obj.get('hotel_name'))
                c_time = time.ctime()
                book_obj = MyBookings(user=request.user,
                                      provision_code=provision_code,
                                      hotel_code=hotel_code,
                                      coral_booking_code=book_code,
                                      room_type=room_type,
                                      room_description=room_description,
                                      pax_count=pax_count, pax_names=names,
                                      hotel_name=hotel_name,
                                      price=price, email=mail,
                                      book_time=c_time)

                MyBookings.save(book_obj)
                return render_to_response('main/book_messages.html',
                                          {'messages': 'Book success'})

            else:
                return render_to_response('main/book_messages.html',
                                          {'messages':
                                           'Sorry, error occured when '
                                           'book stage, Please '
                                           'try again later'})
        else:
            return render_to_response('main/book_messages.html',
                                      {'messages': 'Sorry, Current price'
                                                   '  has changed, '

templates/main/book.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    {% load static %}
    {% load my_template_tags %}
    <title>Login</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="{% static 'css/mycss.css' %}" rel='stylesheet'>

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/room.css' %}"/>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>

{% if availability_result.1 == 200 %}

            
    <div class="container">
        <div class="row">
                        
            <div class="col-md-4">
                                
                            
            </div>
            <div class="col-md-4">
                  
                <div class="container_info"
                     style="padding-top:150px; opacity: 0.9;">
                                
                    <div class="panel panel-primary">
                                        
                        <form method="POST" action="{% url 'main:book' %}">
                        {% csrf_token %}
                        <div style="align-content: center; text-align: center">
                             <h1>{{ hotel_name }}</h1>
                            </div>
                        <div>
                            <input type="hidden" name="product_code" value="{{ product_code }}">
                        </div>

                            <div style="align-content: center; text-align: center">
                                {{ final_price }} {{ availability_result.0.currency }}
                            </div>
                            <div style="align-content: center; text-align: center">
                                {{ availability_result.0.meal_type  }}
                            </div>
                            <div style="align-content: center; text-align: center">
                                {{  availability_result.0.rooms.0.room_category }}
                            </div>
                        <div style="align-content: center; text-align: center">
                                {{  availability_result.0.rooms.0.room_description }}
                            </div>
                           <div style="align-content:center; text-align: center">
                                    User Email
                                </div>
                                <div style="align-content:center; text-align: center">
                                    <input type="email"
                                           name="mail"
                                           style="text-align: center"required>
                                </div>
                                                 
                            {% for index in pax_generator %}
                                                    
                                <div style="align-content:center; text-align: center">
                                    Name
                                </div>
                                <div style="align-content:center; text-align: center">
                                    <input type="text"
                                           name="pax_name"
                                           style="text-align: center"required>
                                </div>
                                                    
                                                   {% endfor %}
                               
                            <div style="align-content:center; text-align: center">
                                <input type="submit" class="btn btn-danger"
                                   style="align-items: center; width: 120px;" value="Book"> </input>
                            </div>
                                
                                  
                        </form>
                                    
                    </div>
                                
                            
                </div>
                        
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>


        {% endif %}
    {% if avabilaty_result != 200 %}

           

        {% endif %}

</body>
</html>

templates/main/book_messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
<span class="label label-success">{{ messages }}</span>


</div>
</body>
</html>

templates/main/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>NoRoom</title>
     <title>Login</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="{% static 'css/mycss.css' %}" rel='stylesheet'>

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/room.css' %}"/>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div class="col-xs-3">


    </div>
    <div class="col-xs-6">
        <div style="margin-top: 300px; font-size:40px;color: darkorange; align-content: center;background-color: lightyellow; opacity: 0.8; border: groove; border-color:#f5dd5d;border-width: 10px;border-style: solid; font-family: 'Al Nile'; padding-top: 10px;
padding-left: 10px;padding-right: 10px">
        Sorry, Error Occured, Please Try Again Later
       </div>

        <div style="text-align: center;margin-top: 20px;">
              <a style="height: 50px; padding-top: 13px" href="{% url 'main:index' %}" class="btn btn-primary" >Back To The Search Page</a>

        </div>
    </div>

    <div class="col-xs-3">


    </div>

</div>

</body>
</html>

templates/main/hotels.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    {% load static %}
    {% load my_template_tags %}

    <title>Login</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="{% static 'css/mycss.css' %}" rel='stylesheet'>

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="backgroundimage">

    <div class="container" style="padding-top: 20px;">

        {% for data in hotels_info %}
                    
        <div class="col-xs-4">
                            
            <div class="panel panel-default">
                                    
                <div class="panel-heading">
                    {{ data.hotel_obj_name }}</div>
                                    
                <div class="panel-body" >
                     {{ data.final_price| division }}


                                    <a href=" {% url 'main:rooms' hotel_code=data.hotel_code %}"  class="btn btn-danger" style="float:right">Next</a>

                </div>

                                
            </div>
                 
        </div>      
                {% endfor %}
    </div>
</div>

</body>
</html>

templates/main/index.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title></title>
    {% load static %}

    <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css'/>
        <link href="{% static 'css/mycss.css' %}" rel='stylesheet' type='text/css'/>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords"
          content="Book Your Travel Widget Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design"/>
    <!-- //end-smoth-scrolling -->
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);
    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>

    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <!--webfonts-->
    <link href='//fonts.googleapis.com/css?family=Oleo+Script:400,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet' type='text/css'>
    <!--//webfonts-->
    <style>
        .main {

        }

        .main .facts {
            margin-top: 100px;

            opacity: 0.8;

        }

    </style>
</head>
<body>

<div>
    <div style="margin-right: 150px;">
    <a href=" {% url 'main:mybookings' %}"  class="btn btn-primary" style="float:right">My Bookings</a>
    </div>


<div class="main">
    <form method="GET" action="{% url 'main:hotels' %}">
        <div class="facts">
            <div class="booking-form">
                <div class="online_reservation">
                    <div class="b_room">
                        <div class="booking_room">
                            <div class="reservation">
                                <ul>
                                    <li class="span1_of_1 desti">
                                        <h4>Choose your destination </h4>
                                        <div class="section_dest">
                                            <select name="destination_code">
                                                {% for dst in destinations %}
                                                    <option value="{{ dst.coral_code }}">{{ dst.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="reservation">
                                <ul>
                                    <li class="span1_of_1">
                                        <h5>Check in date </h5>
                                        <div class="book_date">

                                            <input class="date" id="datepicker" type="text" name="check_in_date"
                                                   value="DD-MM-YY" onfocus="this.value = '';"
                                                   onblur="if (this.value == '') {this.value = 'DD-MM-YY';}"
                                                   required="">

                                        </div>

                                    </li>
                                    <li class="span1_of_1 left">
                                        <h5>Check out date </h5>
                                        <div class="book_date">

                                            <input class="date" id="datepicker1" type="text" name="check_out_date"
                                                   value="DD-MM-YY" onfocus="this.value = '';"
                                                   onblur="if (this.value == '') {this.value = 'DD-MM-YY';}"
                                                   required="">

                                        </div>
                                    </li>
                                    <div class="clear"></div>
                                </ul>
                                <div class="groups">
                                    <div class="grid_4 columns">
                                        <h5>Pax</h5>
                                        <select class="custom-select" id="select-4" name="pax">
                                            <option selected="selected">1</option>
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                        </select>
                                    </div>
                                    <div class="grid_5 columns">

                                    </div>
                                    <div class="grid_6 columns">

                                    </div>
                                    <div class="clear"></div>
                                </div>
                                <!---strat-date-piker---->
                                <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}"/>
                                <script src="{% static 'js/jquery-ui.js' %}"></script>
                                <script>
                                    $(function () {
                                        $("#datepicker,#datepicker1").datepicker({"dateFormat": "yy-mm-dd"});
                                    });
                                </script>
                                <!---/End-date-piker---->
                            </div>

                            <div class="date_btn">
                                <form>
                                    <input type="submit" value="Search">
                                </form>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
                <!---->
            </div>
        </div>
    </form>
</div>
<!--start-copyright-->
<div class="copy-right">
    <div class="wrap">
        <p></p>
    </div>

</div>
<!--//end-copyright-->
</div>
</body>
</html>

templates/main/noroom.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>NoRoom</title>
    <title>Login</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="{% static 'css/mycss.css' %}" rel='stylesheet'>

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/room.css' %}"/>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div style="margin-top: 250px;align-content: center;">
        <!-- Default panel contents -->
        <div style="background-color:lightyellow;opacity: 0.8; font-size:40px; text-align: center; color:darkorange; font-family:'Big Caslon';">
            {% if param == 'room_not_ava' %}
                Sorry, Room Not Available



            {% else %}
                Unfortunately, no available rooms match your filter selections


            {% endif %}

        </div>
        {% if param == 'room_not_ava' %}

        <div style="text-align: center;margin-top: 10px;">
                    <a href="{% url 'main:hotel' %}" class="btn btn-primary">Back To The Hotel's Page</a>


                </div>
        {% else %}
        <div style="text-align: center;margin-top: 10px;">
                    <a href="{% url 'main:index' %}" class="btn btn-primary">Back To The Search Page</a>
                </div>
    {% endif %}
    </div>
</div>
</body>
</html>